monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.platform-analog-sound" }
    ]
    actions = {
      update-props = {
        device.description = "Built-in Speaker / Headphone (ES8326)"
      }
    }
  },
  {
    matches = [
      { node.name = "~alsa_output.platform-analog-sound.*" }
    ]
    actions = {
      update-props = {
        node.description = "Speaker / Headphone"
        device.profile.description = "Speaker / Headphone"
        node.nick = "speaker-headphone"
      }
    }
  },
  {
    matches = [
      { node.name = "~alsa_input.platform-analog-sound.*" }
    ]
    actions = {
      update-props = {
        node.description = "Internal Microphone"
        device.profile.description = "Internal Microphone"
        node.nick = "microphone"
      }
    }
  },
  {
    matches = [
      { device.name = "alsa_card.platform-hdmi0-sound" }
    ]
    actions = {
      update-props = {
        device.description = "HDMI Output"
      }
    }
  },
  {
    matches = [
      { node.name = "~alsa_output.platform-hdmi0-sound.*" }
    ]
    actions = {
      update-props = {
        node.description = "HDMI"
        device.profile.description = "HDMI"
        node.nick = "hdmi"
      }
    }
  }
]
