monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.platform-analog-sound.*" }
    ]
    actions = {
      update-props = {
        priority.session = 1200
        priority.driver  = 1200
      }
    }
  }
]
