[/sys/class/leds/battery_charging]
trigger=bq257xx-charger-online

[/sys/class/leds/battery_full]
trigger=cw2017-battery-charging-blink-full-solid

[/sys/class/leds/input2::capslock]
trigger=kbd-capslock

[/sys/class/leds/input2::numlock]
trigger=kbd-numlock

[/sys/class/leds/input2::scrolllock]
trigger=kbd-scrolllock

[/sys/class/leds/input8::capslock]
trigger=kbd-capslock

[/sys/class/leds/input8::compose]
trigger=none
brightness=0

[/sys/class/leds/input8::kana]
trigger=kbd-kanalock

[/sys/class/leds/input8::numlock]
trigger=kbd-numlock

[/sys/class/leds/input8::scrolllock]
trigger=kbd-scrolllock

[/sys/class/leds/mmc0::]
trigger=mmc0
brightness=0

