# See build framework documentation for a detailed explanation of all available switches:
# https://docs.armbian.com/Developer-Guide_Build-Switches/

# This example config file can be issue by running
# ./compile.sh example
# and will output a ready to run image as described below

# ATTENTION:  This file may get out of date since updating the build framework
#             ("git pull" to say) does not automatically update this file.
#             To regenerate an up-to-date sample config simply delete this file.


BOARD=evb-rk3588s       # Build something for the Radxa ROCK 5B as further specified below
BRANCH=edge       # Use _current_ branch which equals to latest available Linux LTS kernel
RELEASE=resolute     # Use Debian Bookworm userspace
KERNEL_CONFIGURE=no  # skip dialog prompt for adjusting the Linux kernel configuration
INSTALL_HEADERS=yes  # Install Linux kernel headers while building. Can be useful for 3rd party drivers
SHARE_LOGS=yes       # Upload logs to Armbian's paste service to share with developers
BUILD_DESKTOP=yes    # Do not install a graphical desktop environment
DESKTOP_ENVIRONMENT=gnome
DESKTOP_TIER=minimal
BUILD_MINIMAL=no     # Install common CLI utils

USE_CCACHE=yes
UBOOT_LOGLEVEL=7
DOWNLOAD_MIRROR=china
MAINLINE_MIRROR=tuna
#UBOOT_MIRROR=github
GITHUB_MIRROR=china
REGIONAL_MIRROR=china
OFFLINE_WORK=no

#PACKAGE_LIST_BOARD="net-tools vim build-essential mesa-utils screenfetch"
PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools hostapd net-tools vim gedit gnome-software ubuntu-desktop-minimal glmark2-es2-wayland yaru-theme-icon yaru-theme-sound build-essential mesa-utils screenfetch chromium ibus-pinyin"

# Use build host DNS server inside chroot instead of default 1.0.0.1
NAMESERVER=$(grep nameserver /etc/resolv.conf|awk '{ print $2 }'| head -n 1)
